version: "3"
services:
    suricata:
        image: jasonish/suricata:4.1
        volumes:
            - "./rules:/var/lib/suricata/rules/"
            - "./update.sh:/update.sh"
        working_dir: "/"
        command: "./update.sh"
